services:
  web:
    build: .
    container_name: jobportal_web
    restart: unless-stopped
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  celery_worker:
    container_name: jobportal_celery_worker
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/code
    command: "celery -A job_portal worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  celery_beat:
    container_name: jobportal_celery_beat
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/code
    command: "celery -A job_portal beat --loglevel=info"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: jobportal_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  static_volume:
